apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gateway-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-gateway
  template:
    metadata:
      labels:
        app: ms-gateway
    spec:
      containers:
        - name: ms-gateway
          image: nuline/ms-gateway
          ports:
            - containerPort: 8888

            # dckr_pat_GbLS3hAnijAsam_pm0Z53fYoWY0

apiVersion: v1
kind: Service
metadata:
  name: ms-gateway-svc
spec:
  selector:
    app: ms-gateway
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer