# ms-admin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-admin-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-admin
  template:
    metadata:
      labels:
        app: ms-admin
    spec:
      containers:
        - name: ms-admin
          image: nuline/ms-admin
          ports:
            - containerPort: 8888

apiVersion: v1
kind: Service
metadata:
  name: ms-admin-svc
spec:
  selector:
    app: ms-admin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer